// @ts-check

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.

 @type {import('@docusaurus/plugin-content-docs').SidebarsConfig}
 */
const sidebars = {
  // A single sidebar generated from the whole docs tree. Client-Developers and
  // Server-Developers appear as expandable categories within it, so navigating
  // into those docs keeps the same left menu (no sidebar swap / lost context).
  DocsSidebar: [{type: 'autogenerated', dirName: '.'}],
};

export default sidebars;
